Output demo.gif
Set WindowBar Colorful
Set TypingSpeed 150ms

Set FontSize 18
Set Width 800
Set Height 460

Type "fsdh create"
Sleep 1s
Enter

Sleep 2s

Type "widgets/myWidget"
Sleep 1s
Enter

Sleep 1s

Type " "
Sleep 2s
Down
Sleep 500ms
Down
Sleep 500ms
Type " "
Sleep 3s
Enter

Sleep 3s

Hide
Sleep 500ms
Type "cd widgets/myWidget"
Enter
Type "clear"
Enter
Sleep 500ms
Show

Type "tree -n"
Sleep 1s
Enter

Sleep 5s

